num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
print("The result of adding the two numbers is:", num1+num2)
print("The result of subtracting the two numbers is:",num1-num2 )
print("The result of multiplying the two numbers is:", num1*num2)
print("The result of dividing the two numbers is:", num1/num2)
